import Head from "next/head";
import Functionalities from "../components/Functionalities";
import Navbar from "../components/Navbar";
import { useSession, signIn, signOut } from "next-auth/react";
import react from "react";
import { getAnalytics } from "firebase/analytics";
import { app } from "../components/Firebase/Firebase";
import SuggestionBox from "../components/SuggestionBox";
import Footer from "../components/Footer";

export default function Home() {
  const { data: session } = useSession();

  react.useEffect(() => {
    const analytics = getAnalytics(app);
  }, []);

  const backgroundStyle = {
    backgroundImage: "url('wallpapers/1.jpg')",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
  };

  return (
    <div className="bg-gray-100 min-h-screen" style={backgroundStyle}>
      <Head>
        <title>Helping you through!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Functionalities />

      {session && (
        <div className="mt-4">
          <p className="text-center">
            You are logged in as <strong>{session.user.name}</strong>
          </p>

          <SuggestionBox />
        </div>
      )}
      <Footer/>
    </div>
  );
}
