import Head from "next/head";
import Functionalities from "../components/Functionalities";
import Navbar from "../components/Navbar";
import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();

  return (
    <div className="bg-gray-100 h-screen">
      <Head>
        <title>Helping you through!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Functionalities />

      {session && (
        <div className="mt-4">
          <p className="text-center">
            You are logged in as <strong>{session.user.name}</strong>
          </p>
        </div>
      )}
    </div>
  );
}
