import Head from "next/head";
import Functionalities from "../components/Functionalities";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Helping you through!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Functionalities />
    </div>
  );
}
